version: "3.9"

services:
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgresql_data:
